### ISSUE TITLE
SOFTPWM does not do anything

### ISSUE THREAD

**Issue by ervion-n** [xtacocorex/CHIP_IO#14] opened 2016-07-24 18:53 UTC
I have CHIP v1.0 and firmware official build headless 4.4 (Python 2.7.9). 

Simply toggling gpio works using this library, but soft pwm does nothing. I have measured both with multimeter and ostilloscope and detected no change in output. I did not get any error messages either.

```
import time
import CHIP_IO.SOFTPWM as PWM
PWM.start("XIO-P7", 50)
time.sleep(5)
PWM.stop("XIO-P7")
PWM.cleanup()
```

**Comment by ervion-n** [comment] 2016-07-24 18:55
However, if I try to change something, i get error 
```
Traceback (most recent call last):
  File "test.py", line 4, in <module>
    PWM.set_frequency("XIO-P7", 10)
RuntimeError: You must start() the PWM channel first
```
using following code:
```
import time
import CHIP_IO.SOFTPWM as PWM
PWM.start("XIO-P7", 50)
PWM.set_frequency("XIO-P7", 10)
time.sleep(5)
PWM.stop("XIO-P7")
PWM.cleanup()
```

**Comment by aninternetof** [comment] 2016-07-25 00:25
@ervion-n, I don't see anything wrong with your code. I'll dig in and try to see what the problem is tomorrow morning.

**Comment by xtacocorex** [comment] 2016-07-25 02:39
Agreed that the code looks good.  There is definitely something goofy going on as I don't get any data in my test code which I just committed.  It essentially creates a thread for listening to a PWM signal from a source.  Source is XIO-P7, Receiver is CSID0.  Just need a test lead hooked between the two pins.

**Comment by aninternetof** [comment] 2016-07-25 12:43
running it line by line, I am seeing it go into PWM.start("XIO-P7", 50) and never return. Now I'm trying to add some debug statements to see why it's getting hung up.

**Comment by xtacocorex** [comment] 2016-07-25 13:42
I didn't test this part of the library after @fordsfords did his mods. :( Maybe the errors were what made it work. :)  [ I had a FORTRAN program in college that would only work if I accessed an array out of bounds, otherwise I wouldn't get the right answer, it was so messed up and confused my friends and I ]

**Comment by aninternetof** [comment] 2016-07-25 13:51
Ok, looks like it's spinning [here in softpwm_set_duty_cycle](https://github.com/xtacocorex/CHIP_IO/blob/master/source/c_softpwm.c#L139), waiting for mutex lock. Now to figure out why...

**Comment by aninternetof** [comment] 2016-07-25 13:52
(obligatory "I swear I saw this working before I committed it")

**Comment by aninternetof** [comment] 2016-07-25 13:58
Ah, I think I see it. I don't unlock the mutex until the very end of softpwm_start(). Meanwhile, in the middle of softwpwm_start(), softpwm_set_duty_cycle() wants to acquire the lock

**Comment by aninternetof** [comment] 2016-07-25 14:30
Ok, it was two things:

- The mutex locking oversight described above
- softpwm_set_frequency() was returning 1 on success instead of 0, so the ASSRT was catching it

I'm about to push up my hotfix branch, but git is complaining "Could not resolve host: github.com" when I push. Not sure what's up with that. Hope to have it resolved shortly.

**Comment by aninternetof** [comment] 2016-07-25 14:34
Ok, there we go! @xtacocorex  or @ervion-n, would somebody mind pulling down the hotfix/softpwm_stall branch and confirm that it makes PWM work for you guys?

**Comment by xtacocorex** [comment] 2016-07-25 14:59
Will do when I get home from work, it'll probably be sometime tonight.

**Comment by fordsfords** [comment] 2016-07-25 21:15
> Ah, I think I see it. I don't unlock the mutex until the very end of softpwm_start(). Meanwhile, in the middle of softwpwm_start(), softpwm_set_duty_cycle() wants to acquire the lock

Oh no!  Was that my screw up?  I did change the mutexing a bit, and I thought I tested it pretty well!

**Comment by xtacocorex** [comment] 2016-07-26 00:40
No worries @fordsfords, there was a lot of stuff going on.  I just verified I get 0's and 1's out in the spwmtest.py script, so I'm going to go ahead and close and merge this to master.  I updated to v0.1.2.  Forgot the proper commit message to reference this issue. :(

**Closed by xtacocorex** 2016-07-26 00:40 UTC
